---

- name: ASCIINEMA RECORDER | Install prerequisites packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip

- name: ASCIINEMA RECORDER | Installation
  pip:
    name: "{{ item }}"
    state: present
    executable: pip3
  with_items:
    - asciinema

- name: ASCIINEMA RECORDER | Configure environment
  lineinfile:
    path: /etc/environment
    line: ASCIINEMA_CONFIG_HOME="/etc/asciinema"
    state: present

- name: ASCIINEMA RECORDER | Manage directories
  file:
    path: /etc/asciinema
    state: directory
    owner: root
    group: root
    mode: 0755

- name: ASCIINEMA RECORDER | Configure recorder
  template:
    src: etc/asciinema/config.j2
    dest: /etc/asciinema/config
    owner: root
    group: root
    mode: 0644
